#define ROOT_DIR "/opt/amel"

#define PID_SUFFIX "-pid"

#define TEMP_CONTROL_PROCESS_NAME "temp-control"
#define PID_CONTROL_PROCESS_NAME  "pid-control"

#define CURRENT_TEMPERATURE "current-temperature"
#define TARGET_TEMPERATURE "target-temperature"

#define NUMBER_OF_SENSORS "number-sensors"

#define CURRENT_TEMPERATURE_FILE ROOT_DIR "/" CURRENT_TEMPERATURE
#define TARGET_TEMPERATURE_FILE  ROOT_DIR "/" TARGET_TEMPERATURE
#define TEMP_CONTROL_PID_FILE    ROOT_DIR "/" TEMP_CONTROL_PROCESS_NAME PID_SUFFIX
#define PID_CONTROL_PID_FILE     ROOT_DIR "/" PID_CONTROL_PROCESS_NAME  PID_SUFFIX
#define NUMBER_OF_SENSORS_FILE   ROOT_DIR "/" NUMBER_OF_SENSORS


#define MIN_TEMP 10.0
#define MAX_TEMP 30.0
#define DEFAULT_TARGET_TEMPERATURE 18.00


#define SAMPLE_RATE 0.2 // in hertz
#define SAMPLE_TIME  1.0/SAMPLE_RATE
#define SERIAL_PORT "/dev/ttyUSB0"