#define ROOT_DIR "/opt/amel"

#define PID_SUFFIX "-pid"

#define TEMP_CONTROL_PROCESS_NAME "temp-control"
#define PID_CONTROL_PROCESS_NAME  "pid-control"

#define CURRENT_TEMPERATURE "current-temperature"
#define TARGET_TEMPERATURE "target-temperature"

#define CURRENT_TEMPERATURE_FILE ROOT_DIR "/" CURRENT_TEMPERATURE
#define TARGET_TEMPERATURE_FILE  ROOT_DIR "/" TARGET_TEMPERATURE
#define TEMP_CONTROL_PID_FILE    ROOT_DIR "/" TEMP_CONTROL_PROCESS_NAME PID_SUFFIX
#define PID_CONTROL_PID_FILE     ROOT_DIR "/" PID_CONTROL_PROCESS_NAME  PID_SUFFIX
#define NUMBER_OF_SENSORS_FILE   ROOT_DIR "/number-sensors"

#define DEFAULT_TARGET_TEMPERATURE 18.00
#define SAMPLE_RATE 1  // in hertz
#define SERIAL_PORT "/dev/ttyUSB0"